export default class Constants {
  static readonly EVENT_HUB_1 = 'event1'
  static readonly EVENT_HUB_2 = 'event2'
  static readonly DOMAIN_NUMBER: number = 0xFF00;
  static readonly TAG: string = '[EntryAbility]';

  static TEXT_HEIGHT: number = 50;
  static DEFAULT_MARGIN: number = 30;
  static FULL_WIDTH: string = '100%';
  static FULL_HEIGHT: string = '100%';
  static DEFAULT_FONT_SIZE: number = 30;
  static DOMAIN: number = 0x0000;
}