export default class Constants {
  static readonly bundleName = 'com.example.myapplication'
  static readonly EntryAbility = 'EntryAbility'

  static readonly EVENT_HUB_1 = 'event1'
  static readonly EVENT_HUB_2 = 'event2'
  static readonly DOMAIN_NUMBER: number = 0xFF00;
  static readonly TAG: string = '[EntryAbility]';
  static readonly TAG_STARTUP_TASK: string = 'TAG_STARTUP_TASK';

  public static readonly BREAK_POINT_SM: string = 'sm';
  public static readonly BREAK_POINT_MD: string = 'md';
  public static readonly BREAK_POINT_LG: string = 'lg';
  public static readonly FULL_WIDTH: string = '100%';
  public static readonly FULL_HEIGHT: string = '100%';
  public static readonly BORDER_WIDTH: number = 0.5;
  public static readonly FOLD_IMAGE_RATE: number = 1.2;

  /* 首页 */
  static readonly PAGES_INDEX = "pages/Index"

  static readonly PATH_navigation = 'pages/navigation/'
  static readonly NavigationListExamplePage = 'NavigationListExamplePage'
  static readonly SystemRouterMapPage = 'SystemRouterMapPage'
  static readonly NavigationSimplePage = 'NavigationSimplePage'
  static readonly NavigationParamsPage = 'NavigationParamsPage'
  static readonly MainPage = 'MainPage'
  static readonly NavigationDialogExample = 'NavigationDialogExample'
  static readonly TabSimplePage = 'TabSimplePage'
  static readonly NavigationExamplePage1 = 'NavigationExamplePage1'
  static readonly NavigationTransitionOnePage = 'NavigationTransitionOnePage'

  static readonly PATH_siwper = 'pages/swiper/'
  static readonly SwiperExamplePage = 'SwiperExamplePage'

  static readonly PAGES_SECOND = "pages/Second"
  static readonly PAGES_PageStartup = "pages/PageStartup"
  static readonly PAGES_OpenLinkPage = "pages/OpenLinkPage"
  static readonly PAGES_EmbeddedUIPages = "pages/EmbeddedUIPages"
  static readonly PAGES_PageSpecifiedAbility = "pages/PageSpecifiedAbility"
  static readonly PAGES_PAGE_EVENTHUB = "pages/Page_EventHub"
  static readonly PAGES_Page_UIAbilityComponentsBasicUsage = "pages/Page_UIAbilityComponentsBasicUsage"
  static readonly PAGES_Page_UIAbilityComponentsInteractive = "pages/Page_UIAbilityComponentsInteractive"
  static readonly PAGES_Page_FromStageModel = "pages/Page_FromStageModel"
  static readonly PAGES_LifeCyclePage = 'pages/LifeCyclePage'
  static readonly PAGES_CounterView = 'pages/CounterView'
  static readonly PAGES_Parent = 'pages/Parent'
  static readonly PAGES_ContextGetPage = 'pages/ContextGetPage'
  static readonly PAGES_ArticleList = 'pages/ArticleList'
  static readonly PAGES_ForEachSort = 'pages/ForEachSort'
  static readonly PAGES_MyComponent = 'pages/MyComponent'
  static readonly PAGES_TextExample = 'pages/TextExample'
  static readonly PAGES_TextInputAreaExample = 'pages/TextInputAreaExample'
  static readonly PAGES_ButtonExample = 'pages/ButtonExample'
  static readonly PAGES_ButtonCase1 = 'pages/ButtonCase1'
  static readonly PAGES_ButtonCase2 = 'pages/ButtonCase2'
  static readonly PAGES_HoverButtonExample = 'pages/HoverButtonExample'
  static readonly PAGES_LoginPage = 'pages/LoginPage'
  static readonly PAGES_CityList = 'pages/CityList'
  static readonly PAGES_SimpleContacts = 'pages/SimpleContacts'
  static readonly PAGES_ContactsList = 'pages/ContactsList'
  static readonly PAGES_ToDoList = 'pages/ToDoList'
  static readonly PAGES_TwoDimensionList = 'pages/TwoDimensionList'
  static readonly PAGES_NestedListPage = 'pages/NestedListPage'
  static readonly PAGES_SwiperCustomAnimationExample = 'pages/SwiperCustomAnimationExample'
  static readonly PAGES_GrideNestDemos = 'pages/GrideNestDemos'
  static readonly PAGES_GridNestListIndex = 'pages/GridNestListIndex'
  static readonly PAGES_GridNestSwiperIndex = 'pages/GridNestSwiperIndex'
  static readonly PAGES_HandleTabsPage = 'pages/HandleTabsPage'

  static readonly PAGES_NavigationExample = 'pages/NavigationExample'
  static readonly PAGES_NavigationDialogExample = 'pages/NavigationDialogExample'

  static readonly PAGES_SystemRouterMapPage = 'pages/SystemRouterMapPage'
  static readonly PAGES_MVVMPage = 'pages/MVVMPage'
  static readonly PAGES_Page_StartModel = 'pages/Page_StartModel'
  static readonly PAGES_PreferencesPage = 'pages/PreferencesPage'
  static readonly PAGES_AnimationPage = 'pages/AnimationPage'
  static readonly PAGES_TransitionAnimationPage = 'pages/TransitionAnimationPage'
  static readonly PAGES_MultipleDialogPage = 'pages/MultipleDialogPage'
  static readonly PAGES_ElectronicAlbumPage = 'pages/ElectronicAlbumPage'
  static readonly PAGES_SelectContactPage = 'pages/SelectContactPage'
  static readonly PAGES_DownloadNotificationPage = 'pages/DownloadNotificationPage'
  static readonly PAGES_LifecyclePages = 'pages/LifecyclePages'
  static readonly PAGES_statev1_StateV1Page = 'pages/statev1/StateV1Page'
  static readonly PAGES_statev1_StateV1Page2 = 'pages/statev1/StateV1Page2'
  static readonly PAGES_statev2_StateV2Page = 'pages/statev2/StateV2Page'
  static readonly PAGES_statev2_StateV2Page2 = 'pages/statev2/StateV2Page2'


  static readonly PAGES_arkts_PromiseAsyncAwaitPage = 'pages/arkts/PromiseAsyncAwaitPage'
  static readonly PAGES_arkts_WorkerPage = 'pages/arkts/WorkerPage'
  static readonly PAGES_arkts_TaskPoolPage = 'pages/arkts/TaskPoolPage'
  static readonly PAGES_arkts_ComNormalPage = 'pages/arkts/ComNormalPage'
  static readonly PAGES_arkts_ComArrayBufferPage = 'pages/arkts/ComArrayBufferPage'
  static readonly PAGES_arkts_sendable_AsynchronousLockPage = 'pages/arkts/sendable/AsynchronousLockPage'
  static readonly PAGES_arkts_sendable_ASONPage = 'pages/arkts/sendable/ASONPage'
  static readonly PAGES_arkts_sendable_SharedContainerPage = 'pages/arkts/sendable/SharedContainerPage'
  static readonly PAGES_arkts_sendable_SendableObjectFreezePage = 'pages/arkts/sendable/SendableObjectFreezePage'
  static readonly PAGES_arkts_sendable_SendableClassPage = 'pages/arkts/sendable/SendableClassPage'

  static readonly PAGES_arkts_Com1Page = 'pages/arkts/com1/Com1Page'
  static readonly PAGES_arkts_Com2Page = 'pages/arkts/com1/Com2Page'
  static readonly PAGES_arkts_Com3Page = 'pages/arkts/com1/Com3Page'
  static readonly PAGES_arkts_Com4Page = 'pages/arkts/com1/Com4Page'

  static readonly CpuPage = 'pages/arkts/multithread/CPU_CpuPage'
  static readonly WorkThreadPage = 'pages/arkts/multithread/CPU_WorkThreadPage'
  static readonly IO_IoPage = 'pages/arkts/multithread/IO_IoPage'
  static readonly MUL_TaskPoolPage = 'pages/arkts/multithread/MUL_TaskPoolPage'
  static readonly MUL_WorkerPage = 'pages/arkts/multithread/MUL_WorkerPage'
  static readonly LongTaskPoolPage = 'pages/arkts/multithread/LongTaskPoolPage'
  static readonly LongWorkerPage = 'pages/arkts/multithread/LongWorkerPage'

  static readonly TaskPoolDatasPage = 'pages/arkts/threadexample/DatasTaskPoolPage'
  static readonly SharedTaskPoolPage = 'pages/arkts/threadexample/SharedTaskPoolPage'
  static readonly CalculatorTaskPoolPage = 'pages/arkts/threadexample/CalculatorTaskPoolPage'
  static readonly ConfigTaskPoolPage = 'pages/arkts/threadexample/ConfigTaskPoolPage'
  static readonly SendableUpdatePage = 'pages/arkts/threadexample/SendableUpdatePage'
  static readonly SendableObjTestPage = 'pages/arkts/threadexample/SendableObjTestPage'
  static readonly WaterFlowTaskPoolPage = 'pages/arkts/threadexample/WaterFlowTaskPoolPage'

  static readonly RowColumnPage = 'pages/viewgroup/RowColumnPage'
  static readonly StackPage = 'pages/viewgroup/StackPage'
  static readonly StackExamplePage = 'pages/viewgroup/StackExamplePage'
  static readonly FlexExamplePage = 'pages/viewgroup/FlexExamplePage'
  static readonly RelativeContainerPage = 'pages/viewgroup/RelativeContainerPage'
  // static readonly RelativeContainerPage = 'pages/viewgroup/RelativeContainerPage'
  static readonly MediaQueryPage = 'pages/viewgroup/MediaQueryPage'
  static readonly ListExamplePage = 'pages/viewgroup/ListExamplePage'
  static readonly GridGridItemPage = 'pages/viewgroup/GridGridItemPage'
  static readonly GridNestDemos = 'pages/viewgroup/GridNestDemos'
  static readonly GridNestListIndex = 'pages/viewgroup/GridNestListIndex'
  static readonly GridNextSwiperIndex = 'pages/viewgroup/GridNextSwiperIndex'
  static readonly GridCalculator = 'pages/viewgroup/GridCalculator'
  static readonly GridCalc2 = 'pages/viewgroup/GridCalc2'
  static readonly GridNestSwiperIndex = 'pages/viewgroup/GridNestSwiperIndex'
  static readonly SwiperShortVideoPage = 'pages/viewgroup/SwiperShortVideoPage'
  static readonly TabsMultiTabNavigationPage = 'pages/viewgroup/TabsMultiTabNavigationPage'

  static readonly ToDoListPage = 'pages/todo/ToDoListPage'
  static readonly ToDoList = 'pages/todo/ToDoList'

  static readonly Immersive1Page = 'pages/Immersive/Immersive1Page'
  static readonly Immersive2Page = 'pages/Immersive/Immersive2Page'
  static readonly Immersive3Page = 'pages/Immersive/Immersive3Page'
  static readonly Immersive4Page = 'pages/Immersive/Immersive4Page'
  static readonly Immersive5Page = 'pages/Immersive/Immersive5Page'
  static readonly Immersive6Page = 'pages/Immersive/Immersive6Page'

  static readonly ButtonExamplePage = 'pages/component/ButtonExamplePage'
  static readonly RatioExamplePage = 'pages/component/RatioExamplePage'
  static readonly ToggleExamplePage = 'pages/component/ToggleExamplePage'
  static readonly ProgressExamplePage = 'pages/component/ProgressExamplePage'
  static readonly ImageExamplePage = 'pages/component/ImageExamplePage'
  static readonly VideoExample1Page = 'pages/component/VideoExample1Page'
  static readonly VideoShowIndex = 'pages/component/VideoShowIndex'

  static readonly TextSpanPage = 'pages/text/TextSpanPage'
  static readonly TextExample = 'pages/text/TextExample'
  static readonly TextInputTextAreaExamplePage = 'pages/text/TextInputTextAreaExamplePage'
  static readonly RichEditorExamplePage = 'pages/text/RichEditorExamplePage'
  static readonly RichEditorContentPublisherHome = 'pages/text/RichEditorContentPublisherHome'
  static readonly SymbolGlyphSymbolSpanPage = 'pages/text/SymbolGlyphSymbolSpanPage'
  static readonly StyleStringMutableStyleStringPage = 'pages/text/StyleStringMutableStyleStringPage'

  static readonly DialogExamplePage = 'pages/dialog/DialogExamplePage'
  static readonly CustomDialogExamplePage = 'pages/dialog/CustomDialogExamplePage'
  static readonly FixedStyleDialogPage = 'pages/dialog/FixedStyleDialogPage'
  static readonly MenuExamplePage = 'pages/dialog/MenuExamplePage'
  static readonly PopupExamplePage = 'pages/dialog/PopupExamplePage'
  static readonly ModalHalfExamplePage = 'pages/dialog/ModalHalfExamplePage'
  static readonly ModalFullExamplePage = 'pages/dialog/ModalFullExamplePage'
  static readonly ToastExamplePage = 'pages/dialog/ToastExamplePage'
  static readonly OverlayManagerExamplePage = 'pages/dialog/OverlayManagerExamplePage'
  static readonly ShapeExamplePage = 'pages/canvas/ShapeExamplePage'
  static readonly CanvasExamplePage = 'pages/canvas/CanvasExamplePage'
  static readonly CustomCanvasPage = 'pages/canvas/CustomCanvasPage'

  static readonly ShuXingAnimatePage = 'pages/animate/ShuXingAnimatePage'
  static readonly ZhuanChangAnimatePage = 'pages/animate/ZhuanChangAnimatePage'
  static readonly MoTaiAnimatePage = 'pages/animate/MoTaiAnimatePage'
  static readonly ShareAnimate1Page = 'pages/animate/ShareAnimate1Page'
  static readonly ShareAnimateStackPage = 'pages/animate/ShareAnimateStackPage'
  static readonly ShareAnimateNavigationPage = 'pages/animate/ShareAnimateNavigationPage'
  static readonly ShareAnimateBindSheetPage = 'pages/animate/ShareAnimateBindSheetPage'
  static readonly GeometryTransitionTwoPage = 'pages/animate/GeometryTransitionTwoPage'
  static readonly GeometryTransitionOnePage = 'pages/animate/GeometryTransitionOnePage'
  static readonly XuanZhuanPingAnimatePage = 'pages/animate/XuanZhuanPingAnimatePage'
  // src/main/ets/pages/TransitionCollectionPage.ets
  static readonly TransitionCollectionPage = 'pages/animate/TransitionCollectionPage'
  static readonly ParticleExamplePage = 'pages/animate/ParticleExamplePage'
  static readonly ComponentAnimatePage = 'pages/animate/ComponentAnimatePage'
  static readonly AnimationCollectionPage = 'pages/animate/AnimationCollectionPage'
  static readonly TranditionCurvePage = 'pages/animate/TranditionCurvePage'
  static readonly SpringCurvePage = 'pages/animate/SpringCurvePage'
  static readonly AnimationToAnimationPage = 'pages/animate/AnimationToAnimationPage'
  static readonly FrameAnimationPage = 'pages/animate/FrameAnimationPage'
  static readonly AnimateColorPage = 'pages/animate/AnimateColorPage'
  static readonly AnimateBlurPage = 'pages/animate/AnimateBlurPage'
  static readonly AnimateShadowPage = 'pages/animate/AnimateShadowPage'

  static readonly SysColorPage = 'pages/system/SysColorPage'
  static readonly SysStringPage = 'pages/system/SysStringPage'
  static readonly SysMediaPage = 'pages/system/SysMediaPage'
  static readonly SysSymbolPage = 'pages/system/SysSymbolPage'
  static readonly SysFloatPage = 'pages/system/SysFloatPage'

  static readonly TouchEventExamplePage = 'pages/touch/TouchEventExamplePage'
  static readonly BottomDrawerSlideCase = 'pages/touch/BottomDrawerSlideCase'
  static readonly FocusEventPage = 'pages/touch/FocusEventPage'
  static readonly DragFrameworkPage = 'pages/touch/DragFrameworkPage'
  static readonly DragEvent1Page = 'pages/touch/DragEvent1Page'
  static readonly DragEvent2Page = 'pages/touch/DragEvent2Page'
  static readonly GSBindGesturePage = 'pages/touch/GSBindGesturePage'
  static readonly GSSingleGesturePage = 'pages/touch/GSSingleGesturePage'
  static readonly GSGroupGesturePage = 'pages/touch/GSGroupGesturePage'
  static readonly GSMultiLevelGesturePage = 'pages/touch/GSMultiLevelGesturePage'
  static readonly GestureJudgeResultPage = 'pages/touch/GestureJudgeResultPage'
  static readonly GestureFatherControlChildPage = 'pages/touch/GestureFatherControlChildPage'
  static readonly NodeContainerPage = 'pages/customnode/NodeContainerPage'
  static readonly NodeContainer2Page = 'pages/customnode/NodeContainer2Page'
  static readonly CustomFrameNode1Page = 'pages/customnode/CustomFrameNode1Page'
  static readonly CustomFrameNode2Page = 'pages/customnode/CustomFrameNode2Page'
  static readonly CustomFrameNode3Page = 'pages/customnode/CustomFrameNode3Page'
  static readonly CustomFrameNode4Page = 'pages/customnode/CustomFrameNode4Page'
  static readonly CustomFrameNode5Page = 'pages/customnode/CustomFrameNode5Page'
  static readonly CustomFrameNode6Page = 'pages/customnode/CustomFrameNode6Page'
  static readonly CustomFrameNode7Page = 'pages/customnode/CustomFrameNode7Page'
  static readonly RenderNode1Page = 'pages/customnode/RenderNode1Page'
  static readonly RenderNode2Page = 'pages/customnode/RenderNode2Page'
  static readonly RenderNode3Page = 'pages/customnode/RenderNode3Page'
  static readonly RenderNode4Page = 'pages/customnode/RenderNode4Page'
  static readonly BuilderNode1Page = 'pages/customnode/BuilderNode1Page'
  static readonly BuilderNode2Page = 'pages/customnode/BuilderNode2Page'
  static readonly BuilderNode3Page = 'pages/customnode/BuilderNode3Page'
  static readonly AttributeModifierPage = 'pages/customnode/AttributeModifierPage'
  static readonly SideBarContainerExample = 'pages/old/SideBarContainerExample'
  static readonly TextPickerExample = 'pages/old/TextPickerExample'
  static readonly DisplayAllPage = 'pages/theme/DisplayAllPage'

  static readonly SysCapListPage = 'pages/syscap/SysCapListPage'

  static readonly WebUserAgentPage = 'pages/web/WebUserAgentPage'
  static readonly WebComponent = 'pages/web/WebComponent'
  static readonly WebHeightPage = 'pages/web/WebHeightPage'
  static readonly WebNestedScroll = 'pages/web/WebNestedScroll'

  static readonly LongTaskPage = 'pages/task/LongTaskPage'
  static readonly DelayTaskPage = 'pages/task/DelayTaskPage'

  static readonly PasteBoardPage = 'pages/permission/PasteBoardPage'
  static readonly PhotoAccessHelperPage = 'pages/permission/PhotoAccessHelperPage'
  static readonly GeoLocationManagerPage = 'pages/permission/GeoLocationManagerPage'

  static readonly HandWritingComponent = 'pages/hand/HandWritingComponent'
  static readonly PointPredictorDemo = 'pages/hand/PointPredictorDemo'

  static readonly SensorListPage = 'pages/sensor/SensorListPage'

  static readonly TSExamplePage = 'pages/ts/TSExamplePage'

  static readonly TabsExamplePage = 'pages/tab/TabsExamplePage'

  static readonly LOAD_ENTRY_PAGE = Constants.PAGES_INDEX

  static readonly ANCHOR_PARENT = '__container__'
  static readonly __CONTAINER__ = '__container__'

  static TEXT_HEIGHT: number = 50;
  static DEFAULT_MARGIN: number = 30;
  static DEFAULT_FONT_SIZE: number = 30;
  static DOMAIN: number = 0x0000;

  static readonly FULL_PERCENT: string = '100%';
  static readonly TEXT_SCROLL_DURATION: number = 5000;
  static readonly ANGLE_DEGREE: number = 180;
  static readonly FIFTY_PERCENT: string = '50%';
  static readonly ANGLE_DEGREE_HORIZONTAL: number = 90;
  static readonly FONT_WEIGHT_500: number = 500;

  public static readonly FULL_LENGTH: string = '100%';
  public static readonly TITLE_WIDTH: string = '80%';
  public static readonly LIST_DEFAULT_WIDTH: string = '93.3%';
  public static readonly OPACITY_DEFAULT: number = 1;
  public static readonly OPACITY_COMPLETED: number = 0.4;
  public static readonly BORDER_RADIUS: number = 24;
  public static readonly FONT_WEIGHT: number = 500;
  public static readonly COLUMN_SPACE: number = 16;
  public static readonly TODO_DATA: Array<Resource> = [
    $r('app.string.todo_list_one'),
    $r('app.string.todo_list_two'),
    $r('app.string.todo_list_three'),
    $r('app.string.todo_list_four'),
    $r('app.string.todo_list_five')
  ];

  static readonly PERCENT_12: string = '12%';
  static readonly PERCENT_FULL: string = '100%';
  /**
   * MultiTabNavigationPage content width.
   */
  static readonly INDEX_CONTENT_WIDTH: string = '91.1%';
  /**
   * MultiTabNavigationPage divider height.
   */
  static readonly DIVIDER_HEIGHT: number = 0.5;
  /**
   * MultiTabNavigationPage divider width.
   */
  static readonly DIVIDER_WIDTH: string = '93%';
  /**
   * Drawer divider width.
   */
  static readonly DIVIDER_DRAWER_WIDTH: string = '90%';
  /**
   * Card title height.
   */
  static readonly CARD_TITLE_HEIGHT: number = 20;
  /**
   * Card text height.
   */
  static readonly CARD_TEXT_HEIGHT: number = 48;
  /**
   * MultiTabNavigationPage title height.
   */
  static readonly INDEX_TITLE_HEIGHT: number = 112;
  /**
   * Font size of unchecked title.
   */
  static readonly FONT_SIZE_UNCHECKED = 18;
  /**
   * Font size of checked title.
   */
  static readonly FONT_SIZE_CHECKED: number = 24;
  /**
   * Content height.
   */
  static readonly CONTENT_HEIGHT: number = 300;
  /**
   * List height.
   */
  static readonly LIST_HEIGHT: number = 48;
  /**
   * List card width.
   */
  static readonly LIST_CARD_WIDTH: number = 272;
  /**
   * List card height.
   */
  static readonly LIST_CARD_HEIGHT: number = 344;
  /**
   * List content height.
   */
  static readonly LIST_CONTENT_HEIGHT: string = '110%';
  /**
   * Background tab height.
   */
  static readonly BACKGROUND_TAB_HEIGHT: number = 40;
  /**
   * MultiTabNavigationPage button height.
   */
  static readonly INDEX_BUTTON_HEIGHT: number = 60;
  /**
   * Background tab width.
   */
  static readonly BACKGROUND_TAB_WIDTH: number = 96;
  /**
   * Drawer width.
   */
  static readonly DRAWER_WIDTH: number = 264;
  /**
   * Sub tab width.
   */
  static readonly SUB_TAB_WIDTH: number = 56;
  /**
   * Sub slide width.
   */
  static readonly SUB_SLIDE_TAB_WIDTH: number = 56;
  /**
   * Sub tab bottom height.
   */
  static readonly SUB_TAB_BOT_HEIGHT: number = 25;
  /**
   * Sub tab width.
   */
  static readonly SUB_TAB_HEIGHT: number = 30;
  /**
   * Sub list width.
   */
  static readonly SUB_LIST_WIDTH: string = '85%';
  /**
   * Side tab width.
   */
  static readonly SIDE_TAB_WIDTH: string = '27.8%';
  /**
   * Side contend width.
   */
  static readonly SIDE_CONTEND_WIDTH: string = '72.2%';
  /**
   * Tab index0.
   */
  static readonly TAB_INDEX_ZERO: number = 0;
  /**
   * Tab index1.
   */
  static readonly TAB_INDEX_ONE: number = 1;
  /**
   * Tab index2.
   */
  static readonly TAB_INDEX_TWO: number = 2;
  /**
   * Tab index3.
   */
  static readonly TAB_INDEX_THREE: number = 3;
  /**
   * Tab index4.
   */
  static readonly TAB_INDEX_FOUR: number = 4;
  /**
   * Tab index5.
   */
  static readonly TAB_INDEX_FIVE: number = 5;
  /**
   * Image tab size.
   */
  static readonly IMAGE_SIZE_TAB: number = 22;
  /**
   * Image middle size.
   */
  static readonly IMAGE_SIZE_MIDDLE: number = 56;
  /**
   * Tab padding.
   */
  static readonly TAB_PADDING: number = 12;
  /**
   * More image width.
   */
  static readonly MORE_IMAGE_WIDTH: number = 20;
  /**
   * More image height.
   */
  static readonly MORE_IMAGE_HEIGHT: number = 15;
  /**
   * More image row width.
   */
  static readonly MORE_IMAGE_ROW_WIDTH: number = 60;
  /**
   * Drawer image height or width.
   */
  static readonly DRAWER_IMAGE_HEIGHT_WIDTH: number = 24;
  /**
   * List image height or width.
   */
  static readonly LIST_IMAGE_HEIGHT_WIDTH: number = 40;
  /**
   * Image offset.
   */
  static readonly IMAGE_OFFSET: number = -15;
  /**
   * Icon offset.
   */
  static readonly ICON_Offset: number = -3;
  /**
   * Animation duration.
   */
  static readonly ANIMATION_DURATION: number = 0;
  /**
   * Margin sixteen.
   */
  static readonly MARGIN_SIXTEEN: number = 16;
  /**
   * Margin button top.
   */
  static readonly MARGIN_BUTTON_TOP: number = 48;
  /**
   * Translate top.
   */
  static readonly TRANSLATE_TOP: number = -40;
  /**
   * Translate bottom.
   */
  static readonly TRANSLATE_BOTTOM: number = 40;
  /**
   * Border radius drawer.
   */
  static readonly BORDER_RADIUS_DRAWER: number = 16;
  /**
   * Border radius index list.
   */
  static readonly BORDER_RADIUS_INDEX_LIST: number = 18;
  /**
   * Border radius drawer content.
   */
  static readonly BORDER_RADIUS_DRAWER_CONTENT: number = 20;
  /**
   * Border radius back tab.
   */
  static readonly BORDER_RADIUS_BACK_TAB: number = 21;
  /**
   * Divider strokeWidth.
   */
  static readonly STROKE_WIDTH: number = 2;
  /**
   * Slice index index0.
   */
  static readonly SLICE_INDEX_ZERO: number = 0;
  /**
   * Slice index index6.
   */
  static readonly SLICE_INDEX_SIX: number = 6;
  /**
   * fontWeight.
   */
  static readonly FONT_WEIGHT_TAB: number = 600;
  /**
   * TopTabData.
   */
  static readonly TOP_TAB_DATA: Array<Resource | string> =
    [$r('app.string.literature'), $r('app.string.making_friends'), $r('app.string.live_broadcast'),
      $r('app.string.video'), $r('app.string.ceremony'), $r('app.string.play')];
}

/**
 * Route type define.
 */
export interface Route {
  title: string | Resource;
  child: Array<ChildRoute>;
}

/**
 * ChildRoute type define.
 */
export interface ChildRoute {
  text: string | Resource;
  to: string;
}

export const STYLE_CONFIG: Record<string, number> = {
  'IMAGE_SIZE': 32,
  'IMAGE_MARGIN': 4,
  'ICON_GUTTER': 4,
  'OPERATION_BUTTON_PADDING': 4,
  'MENU_IMAGE_SIZE': 24,
  'MENU_HEIGHT': 56,
  'TEXT_MARGIN_LEFT': 40,
  'IMAGE_MARGIN_RIGHT': 30,
  'LIST_ITEM_GUTTER': 12,
  'BORDER_WIDTH': 3,
  'TODO_ITEM_HEIGHT': 80,
  'TODO_ITEM_PADDING_VERTICAL': 4,
  'IMAGE_ICON_OK_SIZE': 15,
  'ANIMATION_DURATION': 600,
  'CUSTOM_CHECKBOX_SIZE': 20
}

export class Constant {
  /**
   * Percent 12.
   */
  static readonly PERCENT_12: string = '12%';

  /**
   * Percent 100
   */
  static readonly PERCENT_FULL: string = '100%';
}